FROM nginx:1.23.2

COPY nginx.conf /etc/nginx/nginx.conf

COPY storage/harness-download /www/storage/harness-download
COPY storage/wingsdelegates /www/storage/wingsdelegates
COPY storage/wingswatchers /www/storage/wingswatchers
